server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /data/ {
        add_header Cache-Control "public, max-age=300";
        try_files $uri =404;
    }

    gzip on;
    gzip_types application/json application/javascript text/css image/svg+xml;
}
